### ISSUE TITLE
Automatic update check does not work at start

### ISSUE THREAD

**Issue by Drumaster78** [NiyaShy/XB1ControllerBatteryIndicator#25] opened 2019-04-25 15:30 UTC
Hello and thanks for this new 1.3.0 release, I'm still using your app on my pc. :)

One little bug though: the automatic update check at launch does not work and does not say that a new version is out. I noticed 1.3.0 version by coming on this page after a few months.

To get the update notification to appear, you have to uncheck the option (right click and 'Check new version on start') then check it again.

Keep up the good work!

**Comment by NiyaShy** [comment] 2019-04-25 16:14
Hey,

I feared this was the case, just never had the time to try it out for confirmation. So thanks for letting me know, I'll look into it.

**Comment by NiyaShy** [comment] 2019-05-01 12:14
Found the cause. As stupid as it sounds, it was forgotten to actually call the "check for updates" routine on startup, so it was only called when you check the option.
Will get fixed with the next version.

**Comment by Drumaster78** [comment] 2019-05-01 13:40
Great, thanks. :)

**Comment by NiyaShy** [comment] 2019-06-18 19:01
Just uploaded the new version that includes the fix. So from now on update check should work as intended ;)

**Closed by NiyaShy** 2019-06-18 19:01 UTC
Labels: Implemented/fixed and released, bug
