### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by L0neWarri0r** [NiyaShy/XB1ControllerBatteryIndicator#2] opened 2018-04-06 06:30 UTC
Thx for this usefull app, it wold be great, if you also make intant gamepad disconnect option\button )

**Comment by illusive-man** [comment] 2018-04-06 08:52
Agree. I love your app and we want it even better! ))
1. It would be great to have charge level in percentage not High/Medium/Low if possible.
2. Notification exits from the full screen app when invoked, making it unresponsive for short period of time. 
3. It's impossible to press "Shut up already" if #2 has occurred.

Otherwise great app. Thanks for your work!

**Comment by NiyaShy** [comment] 2018-04-07 16:14
I just looked into the documentation of the SharpDX library that I'm using to get data from the controller, and according to documentation there is no way to send data to the controller (other than getting it to rumble). So what you want is not doable with the current libraries/APIs. I'd probably have to rewrite the whole thing from scratch, and that's... a bit too much for such a small "issue". Especially since there are already tools available that do what you want.

**Comment by illusive-man** [comment] 2018-04-09 12:16
@L0neWarri0r what's wrong with the long press of the Xbox Button to turn the controller off?!

@NiyaShy, yep. I was playing Mass Effect: Andromeda, Win10Pro x64, pretty nice rig with SSDs. It (low battery notification) did stole the focus, Mass Effect became minimized and unresponsive for like 20secs, but trying to press "Shut up already" (or anywhere in the notification area) gave me nothing. I had to quit your app forcefully via tray. I will try to reproduce that soon and will get back to you then.

**Comment by L0neWarri0r** [comment] 2018-04-09 14:58
@illusive-man I didn't know of this feature on xbox one gamepad, 360's doesen't have it =)

**Comment by NiyaShy** [comment] 2018-04-09 16:36
@L0neWarri0r the long press thing was mentioned on the description of the tool you linked ;) So I guess that tool only works with 360 controllers and isn't necessary for XBOne ones.

@illusive-man Thanks for the clarification. That the toast (those messages are officially called that way) stole focus is more or less a windows issue... The tool basically just tells windows "hey, I have a notification here, please display it to the user with these options".
And, on startup, it registers with windows with a unique ID to be able to send and react to toasts. So when you click anywhere on the toast, Windows sends a note back to the tool "hey, user clicked on the toast and triggered event X" (that event depends on if you click on the "body" of the toast or on the button).
So, with that in mind it is kinda weird that you had to force it to quit to get rid of the toast. After all Windows handles the toast and the tool just sends and waits for a reply. It was probably "fixed" by the force quit since that killed the toast registration.

Have you ever had other toasts (like from windows update or some other program) while gaming? That would be the "cross test" if it's a general toast issue or specific to the one the tool triggers.
Then again, there is a slight difference between those toasts. The usual "hey, I installed updates and want a reboot" toast gets displayed for a few seconds and then retreats to the notification center. The ones the tool triggers are meant as "alarm" or "reminder" toasts that stay on the screen until you interact with them. 
I just did a quick test, you can force a "reminder" toast with the small "Microsoft to-do" app from the MS store. Add a new to-do point and set it to remind you at a certain time. Would be interesting to know if such toast behaves the same and forces ME:A to minimize. Could you try that out?

**Comment by illusive-man** [comment] 2018-04-10 09:56
@L0neWarri0r, sorry mate. This app is called "XBOX ONE Controller Battery Indicator", so I supposed you have one. )) 

@NiyaShy, thanks for detailed reply. I understand all the principles the toasts operate, but no other toasts have ever interfered with any full screen apps (specifically games) before. That's why I was surprised and decided to inform you. BTW I don't know if it help but I have triple monitor setup and I'm gaming only on one of them (not surround setup).

As for quick test I have alarm set up while I'm gaming ME:A. But it behaves differently. When alarm triggers I can hear it's ringing but toast doesn't steal the focus or minimizes ME:A.  

My controller's chargeable batteries are at full now so I will try and reproduce that behavior with your app later when they dry. 

Anyway it's not a big deal and your app is still the best!

**Comment by L0neWarri0r** [comment] 2018-04-10 11:00
@illusive-man у меня есть оба, просто недавно купил от вана, не знал, что его можно на кнопку выключить )

**Comment by NiyaShy** [comment] 2018-04-16 16:06
Thanks for the feedback. Not being able to close it is yet another weird thing... But as I already mentioned, that sounds more like a windows issue.

We'll see what 1803 brings, hopefully it won't break the notification like 1709 did xD

**Comment by NiyaShy** [comment] 2018-06-22 23:31
Since I haven't heard anything from either of you for a while I'll take the liberty of closing this issue.

**Closed by NiyaShy** 2018-06-22 23:31 UTC
